// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iawkiebnoclcgteyiaji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhd2tpZWJub2NsY2d0ZXlpYWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTMzNjYsImV4cCI6MjA2NDk4OTM2Nn0.CTSJxhLB-xTHFjyvKgfxjlEdKPfxZbnQBx8ndhMnxXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);